spring:
  application:
    name: graphql
  datasource:
    url: jdbc:postgresql://localhost:5432/usuarios_db
    username: postgres
    password: carlos
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  graphql:
    websocket:
      path: /graphql
    graphiql:
      enabled: true
    #schema:
     # locations: classpath:/graphql/
